/**
 * 这是一个示例文件，展示如何使用本地字体文件
 * 如果你有自定义字体，可以参考这个文件修改 layout.tsx
 */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local"; // 导入本地字体加载器
import "./globals.css";
import I18nProvider from "@/components/i18n/I18nProvider";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

// ============================================
// 方式一：继续使用 Google Fonts（当前方式）
// ============================================
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ============================================
// 方式二：使用本地字体文件（示例）
// ============================================
// 如果你有自定义字体文件，取消下面的注释并修改路径

/*
const customFont = localFont({
  src: [
    {
      path: '../fonts/CustomFont-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../fonts/CustomFont-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../fonts/CustomFont-Italic.woff2',
      weight: '400',
      style: 'italic',
    },
  ],
  variable: '--font-custom',
  display: 'swap', // 字体加载策略：swap 表示先显示备用字体，字体加载后再切换
});

// 或者单个字体文件
const singleFont = localFont({
  src: '../fonts/MyFont.woff2',
  variable: '--font-single',
  display: 'swap',
});
*/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        // 如果使用本地字体，添加到这里：
        // className={`${geistSans.variable} ${geistMono.variable} ${customFont.variable} antialiased`}
      >
        <I18nProvider>
          <Navbar />
          {children}
          <Footer />
        </I18nProvider>
      </body>
    </html>
  );
}

/**
 * 使用说明：
 * 
 * 1. 将字体文件放在项目根目录的 fonts/ 文件夹中
 * 2. 取消上面的注释，修改字体路径和变量名
 * 3. 在 body 的 className 中添加字体变量
 * 4. 在 globals.css 中使用 CSS 变量：
 *    font-family: var(--font-custom);
 * 
 * 字体文件格式推荐：
 * - .woff2（最佳，文件小，现代浏览器都支持）
 * - .woff（备选，兼容性更好）
 * - .ttf/.otf（不推荐，文件太大）
 */

