import type { Metadata } from "next";
// import { Geist, Geist_Mono,} from "next/font/google";
import "./globals.css";
import I18nProvider from "@/components/i18n/I18nProvider";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import localFont from "next/font/local";


// 一个文件就能覆盖所有字重（100-900）和样式，文件更小，性能更好
const bitcountFont = localFont({
  src: '../fonts/Bitcount_Prop_Single/BitcountPropSingle-VariableFont_CRSV,ELSH,ELXP,slnt,wght.ttf',
  variable: '--font-bitcount',
  display: 'swap',
  weight: '100 900', 
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${bitcountFont.variable} antialiased container-custom`}
      >
        <I18nProvider>
          <Navbar />
          {children}
          <Footer />
        </I18nProvider>
      </body>
    </html>
  );
}
